# Generated by Django 3.0.6 on 2020-06-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='time',
            field=models.CharField(default='hello', max_length=50),
        ),
    ]
