# Generated by Django 3.0.6 on 2020-06-07 05:25

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_issuebooks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebooks',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issuebooks',
            name='expiry_date',
            field=models.DateField(default=books.models.IssueBooks.get_expiry_date),
        ),
    ]
