# Generated by Django 3.0.6 on 2020-06-07 08:07

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200607_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebooks',
            name='entry_date',
            field=models.DateField(default=books.models.IssueBooks.get_entry_date),
        ),
    ]
